### ISSUE TITLE
TASK Enable client and server certificate migrations

### ISSUE THREAD

**Issue by thejhh** [hyperifyio/gocertcenter#124]
## Goal

This task enables to run multiple instances of the `gocertcenter` for client and server certificates

## Subtasks

* [ ] Import a certificate to the service - PUT /organizations/{organization}/certificates/{root}/certificates/{certificate} with application/x-pem-file content
* [ ] Export a certificate from the service - GET /organizations/{organization}/certificates/{root}/certificates/{certificate} with content-type application/x-pem-file
* [ ] Remove a certificate from the service (does not revoke it!) - DELETE /organizations/{organization}/certificates/{root}/certificates/{certificate}
