### ISSUE TITLE
POC Mutual TLS connections between 3rd party server and browser

### ISSUE THREAD

**Issue by thejhh** [hyperifyio/gocertcenter#156]
### Objective

Develop a Proof of Concept (POC) to demonstrate the feasibility of establishing end-to-end encrypted mutual TLS (mTLS) connections from a browser environment using WebAssembly (compiled from Go), with an emphasis on leveraging Go's standard `tls` library and a server-side component for full end-to-end communication. This approach will abstract the network communication over a custom implementation of the `net.Conn` interface to work within the constraints of WebAssembly and WebSockets.

### Subtasks

- [x] **Develop Go Application for mTLS**: Write a simple Go program that uses the `tls` library to establish mTLS connections. Integrate a custom `net.Conn` interface implementation for communication over WebSockets.
- [x] **Compile Go to WebAssembly**: Compile the Go program into a WebAssembly module suitable for execution in web browsers.
- [x] **Implement Server-Side WebSocket to TCP/mTLS Bridge**: Create a server-side component that acts as a bridge, translating WebSocket communication from the Wasm module to TCP/mTLS connections for true end-to-end encryption.
- [x] **Prepare Documentation and Demonstration**: Compile detailed documentation and prepare a demonstration to showcase the capabilities and usage of the POC.

### Expected Challenges

- Ensuring the custom `net.Conn` implementation in Go effectively simulates network communication over WebSockets.
- Maintaining high security and performance standards despite the browser's limitations and the overhead introduced by WebSocket communication.
- Demonstrating the practicality of using Go's `tls` library within a WebAssembly environment for secure, real-world web application communications.

### Executing the POC

Get the source code:

```
git clone -b wasm-mtls-poc git@github.com:hyperifyio/golancenter.git
cd golancenter
```

Compile software and create certificate files:

``` 
make
```

Start up a test server:

```
./testserver
```

This starts up a HTTPS server at https://localhost:8443 which only accepts connections with a valid client certificate.

You can verify it works (or does not) like this:

```sh
curl https://localhost:8443
```

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

And here's how to test with the correct certificate:

```sh
curl --cacert certs/server-ca-chain.pem --cert certs/client-cert.pem --key certs/client-key.pem https://localhost:8443
```

```
Hello World
```

Start up the POC:

```
./golancenter
```

This will actually start another local HTTP server acting as a websocket proxy at http://localhost:8080. It's unsecured, but the data going throught it is TLS encrypted. Suitable for demostration purposes.

Then it starts a frontend running in a webview to demostrate the web browser. Inside the webview, a wasm program starts up, makes a connection to https://localhost:8443, and prints the output to the webpage. 

That's the text "Hello World" displayed in the POC.
