### ISSUE TITLE
TASK CI/CD Pipeline Setup

### ISSUE THREAD

**Issue by thejhh** [hyperifyio/gocertcenter#73]
### Goal
Configure the CI/CD pipeline for automated testing, builds, and deployments.

### Subtasks
* [ ] Configure automated tests.
* [ ] Configure automated builds and deployments.
* [ ] Set up linting and code quality checks.
